services:
  frontend:
    image: frontend:latest
    build: ./web
    container_name: frontend
    working_dir: /powerplay
    volumes:
      - /powerplay/node_modules
      - ./web:/powerplay
    ports:
      - 9000:9000
    environment:
      NODE_ENV: development
    command: bun run dev

  backend:
    image: backend:latest
    build: .
    container_name: backend
    working_dir: /powerplay
    volumes:
      - /powerplay/tmp # Anonymous mount for air temp directory
      - .:/powerplay
    ports:
      - 9002:9002
    depends_on:
      database:
        condition: service_healthy
    command: air -c configs/air/backend.toml

  database:
    image: postgres:16
    container_name: db
    restart: always
    volumes:
      - ./init/db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=powerplay
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
