openapi: 3.1.0
info:
  version: 0.0.0
  title: Power Play API
  description: Developer documentation for the PowerPlay app
  license:
    name: MIT
    url: https://opensource.org/license/mit

paths:
  # http://localhost:9001/docs#post-/
  /auth:
    $ref: "./auth/auth.yml#/paths/auth"
  /user:
    $ref: "./users/users.yml#/paths/user"
  /penalties:
    $ref: "./stats/penalties.yml#/paths/penalties"

  # /[URL path]
  #$ref: "./[Relative path starting from v1]#/paths/[yml path]"
  /goals:
    $ref: "./stats/goal.yml#/paths/goals"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt
