openapi: 3.1.0
info:
  version: 0.0.0
  title: Power Play API
  description: Developer documentation for the PowerPlay app
  license:
    name: MIT
    url: https://opensource.org/license/mit

paths:
  /auth:
    $ref: "./auth/auth.yml#/paths/auth"
  /shotsongoal:
    $ref: "./stats/shotsongoal.yml#/paths/shotsOnGoal"   
  /penaltyTypes:
    $ref: "./stats/penalties.yml#/paths/penaltyTypes"
  /leagues:
    $ref: "./leagues/leagues.yaml#/paths/leagues"
  /penalties:
    $ref: "./stats/penalties.yml#/paths/penalties"
  /user:
    $ref: "./users/users.yml#/paths/user"
  /teams:
    $ref: "./groups/teams.yml#/paths/~1teams"
  /teams/{id}:
    $ref: "./groups/teams.yml#/paths/~1teams~1%7Bid%7D"
  /goals:
    $ref: "./stats/goal.yml#/paths/goals"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt
