leagues:
  - league: A
    teams:
      - name: Reapers
        id: 8387072
      - name: Yetis
        id: 8387074
      - name: Chiefs
        id: 8387070
      - name: Pine Hill
        id: 8387075
      - name: Sharknado
        id: 8387073
      - name: Mountain Men
        id: 8387071
  - league: B
    teams:
      - name: Puck Commanders
        id: 8387065
      - name: Esqeletos
        id: 8387061
      - name: P-Wings
        id: 8387063
      - name: Jr Yetis
        id: 8387062
      - name: Puck Bandits
        id: 8387064
      - name: Rusty Blades
        id: 8387066
  - league: C
    teams:
      - name: Big Willies
        id: 8386949
      - name: The Crew
        id: 8386950
      - name: Neighborhood
        id: 8386951
      - name: Marauders
        id: 8386952
      - name: Rebels
        id: 8386953
      - name: Trash Pandas
        id: 8386968
  - league: D
    teams:
      - name: District 5
        id: 8386972
      - name: Iceholes
        id: 8386973
      - name: Sentinels
        id: 8386974
      - name: Pistol Shrimp
        id: 8386975
      - name: Trashers
        id: 8386976
      - name: Redshift
        id: 8386982

ice_time:
  - 01/22/24 21:00
  - 01/22/24 22:30
  - 01/23/24 21:45
  - 01/24/24 21:00
  - 01/24/24 22:30
  - 01/25/24 22:15
  - 01/26/24 22:15
  - 01/27/24 22:15
  - 01/29/24 21:00
  - 01/29/24 22:30
  - 01/30/24 21:45
  - 01/31/24 21:00
  - 01/31/24 22:30
  - 02/01/24 22:15
  - 02/02/24 20:45
  - 02/02/24 22:15
  - 02/03/24 21:00
  - 02/03/24 22:30
  - 02/05/24 21:00
  - 02/05/24 22:30
  - 02/06/24 21:45
  - 02/07/24 21:00
  - 02/07/24 22:30
  - 02/08/24 22:15
  - 02/09/24 22:15
  - 02/10/24 22:15
  - 02/12/24 21:30
  - 02/13/24 20:45
  - 02/13/24 22:15
  - 02/14/24 21:00
  - 02/14/24 22:30
  - 02/15/24 22:15
  - 02/16/24 22:15
  - 02/17/24 20:45
  - 02/17/24 22:15
  - 02/20/24 20:45
  - 02/20/24 22:15
  - 02/21/24 21:00
  - 02/21/24 22:30
  - 02/22/24 22:15
  - 02/23/24 22:15
  - 02/24/24 22:15
  - 02/26/24 21:30
  - 02/27/24 20:45
  - 02/27/24 22:15
  - 02/28/24 21:00
  - 02/28/24 22:30
  - 02/29/24 22:15
  - 03/01/24 21:15
  - 03/01/24 22:45
  - 03/02/24 20:45
  - 03/02/24 22:15
  - 03/04/24 21:30
  - 03/05/24 20:45
  - 03/05/24 22:15
  - 03/06/24 21:00
  - 03/06/24 22:30
  - 03/11/24 21:30
  - 03/12/24 20:45
  - 03/12/24 22:15
  - 03/13/24 21:00
  - 03/13/24 22:30
  - 03/14/24 22:15
  - 03/15/24 20:45
  - 03/15/24 22:15
  - 03/16/24 20:45
  - 03/16/24 22:15
  - 03/18/24 21:00
  - 03/18/24 22:30
  - 03/19/24 20:45
  - 03/19/24 22:15
  - 03/25/24 21:30
  - 03/26/24 20:45
  - 03/26/24 22:15
  - 03/27/24 20:45
  - 03/27/24 22:15
  - 03/28/24 22:15
  - 03/29/24 20:45
  - 03/29/24 22:15
  - 03/30/24 20:45
  - 03/30/24 22:15
  - 04/01/24 21:30
  - 04/02/24 20:45
  - 04/02/24 22:15
  - 04/03/24 20:45
  - 04/03/24 22:15
  - 04/04/24 20:45
  - 04/04/24 22:15
  - 04/05/24 20:45
  - 04/05/24 22:15
  - 04/06/24 20:45
  - 04/06/24 22:15
  - 04/08/24 21:30
  - 04/09/24 20:45
  - 04/09/24 22:15
  - 04/10/24 20:45
  - 04/10/24 22:15
  - 04/11/24 20:45
  - 04/11/24 22:15
  - 04/12/24 20:45
  - 04/12/24 22:15
  - 04/13/24 20:45
  - 04/13/24 22:15
  - 04/15/24 21:30
  - 04/16/24 20:45
  - 04/16/24 22:15
  - 04/17/24 20:45
  - 04/17/24 22:15
  - 04/18/24 20:45
  - 04/18/24 22:15
  - 04/19/24 20:45
  - 04/19/24 22:15
  - 04/20/24 20:45
  - 04/20/24 22:15
  - 04/22/24 21:30
  - 04/23/24 20:45
  - 04/23/24 22:15
  - 04/24/24 20:45
  - 04/24/24 22:15
  - 04/25/24 20:45